### ISSUE TITLE
X11: Keyevent Alt+F4 doesn't get triggered in Window mode

### ISSUE THREAD

**Issue by Robert42** [LaurentGomila/SFML#274]
When using Window mode Alt+F4 doesn't get pulled as Event.

Normally That's nothing one notices as using sf::Style::Close, results in sending a Close Event.

See the original Topic within the forum: http://en.sfml-dev.org/forums/index.php?topic=8923.0

**Comment by eXpl0it3r** [comment]
[The XCB branch has been merged](b7c0af3a5842011ee6594b44e6b561d1c9515483), as such this issue could be reinvestigated.

**Comment by TankOs** [comment]
:eyes:

**Comment by TankOs** [comment]
Implemented in #780

**Comment by binary1248** [comment]
Implemented in #825 (revised version of #780).

**Comment by binary1248** [comment]
Merged in b9cc6f5c0de4587c70ae9447a1d7a501cefaded1
