### ISSUE TITLE
Access Violation error in the destructor of sf::AudioDevice

### ISSUE THREAD

**Issue by fpoisson** [LaurentGomila/SFML#30]
Access Violation error occurs int the destructor of sf::AudioDevice on Windows XP SP3. It doesn't occur on Windows 7 and Windows Vista. 

Here is the instruction pointed by the visual C++ 2008 debugger: 

Code:

    AudioDevice::~AudioDevice() 
    { 
        // Destroy the context 
        alcMakeContextCurrent(NULL); 
        if (audioContext) 
    =>           alcDestroyContext(audioContext); 

        // Destroy the device 
        if (audioDevice) 
            alcCloseDevice(audioDevice); 
    } 

The error can be reproduced with this simple code :

    #include <SFML/Audio.hpp> 

    int main() 
    { 
        sf::Sound Sound; 

        return EXIT_SUCCESS; 
    } 

This problem was first discussed in this post of the french forum :
http://www.sfml-dev.org/forum-fr/viewtopic.php?t=3443

**Comment by zedfax** [comment]
I've just compiled SFML from master and same problem, my programm exit with value "-1 073 741 515")

**Comment by zsbzsb** [comment]
@zedfax Please open a thread on the forum as I kinda doubt this is your issue.

**Comment by achpile** [comment]
@zsbzsb Got same problem too. May be I'll test it at evening on 2.3.1 or 2.3. But for 2.3.2 got Access Violation.

**Comment by achpile** [comment]
It's very odd. One try out of ten it finished without errors. And the most amazing thing is: it crashes after SoundStream destructor. It just can't call parent (SoundSource) destructor.

**Comment by achpile** [comment]
PS: win7 32bit, minGW 4.9.2

**Comment by mihaicirneala** [comment]
I still have the same problem on Windows 10, with dynamic linking and openal32.dll copied in the same dir with the executable..
