### ISSUE TITLE
SFML Fullscreen on Linux (Elementary OS 64bit) Glitch & Flicker even after close

### ISSUE THREAD

**Issue by derekpock** [LaurentGomila/SFML#535]
```c++
#include <SFML/Graphics.hpp>
#include <iostream>

int main()
{
	sf::RenderWindow window(sf::VideoMode(1366, 768), "SFML works!", sf::Style::Fullscreen);
	//window.setVerticalSyncEnabled(true);
	sf::Image image;
	if(!image.loadFromFile("picture.png")) {
		std::cout << "Error!" << std::endl;
		exit(1);
	}
	sf::Texture texture;
	if(!texture.loadFromImage(image)) {
		std::cout << "Error!" << std::endl;
		exit(1);
	}
	texture.setSmooth(false);
	texture.setRepeated(false);
	sf::Sprite sprite;
	sprite.setTexture(texture);
	while (window.isOpen()) {
		sf::Event event;
		while (window.pollEvent(event)){
			switch(event.type) {
			case sf::Event::KeyPressed:
				std::cout << "key pressed!" << std::endl;
				if(event.key.code==sf::Keyboard::F4 && (sf::Keyboard::isKeyPressed(sf::Keyboard::LAlt) || sf::Keyboard::isKeyPressed(sf::Keyboard::RAlt))) {
					window.close();
				}
				break;
			}
		}
		window.clear();
		window.draw(sprite);
		window.display();
	}
	return 0;
}
```
Simple code, just to get me understanding SFML. It works perfectly when you remove the sf::Style::Fullscreen, but with it, the display glitches. When I close the window, my display continues to glitch and flicker. Only a kill of the window manager (ctrl+alt+back) will stop the flickering. Any ideas? I'll attach the picture.png as well. 64bit Elementary OS 4GRam, 1366x768res. 
![picture](https://f.cloud.github.com/assets/6723267/2203408/9900d7a2-991d-11e3-83d1-4a86bf06fd96.png)

Yes the picture.png looks like my background. It's just something I found and decided to test on.

Here is an uploaded video of my problems. The screencaster is NOT glitching, these are the outcomes of this code. That is more/less what is being displayed on my screen. http://www.youtube.com/watch?v=is-CqqN08Vw&feature=youtu.be

**Comment by eXpl0it3r** [comment]
[The XCB branch has been merged](b7c0af3a5842011ee6594b44e6b561d1c9515483), as such this issue could be reinvestigated.

**Comment by TankOs** [comment]
I'll take a look. :eyes:

**Comment by TankOs** [comment]
@derekpock Feel free to test #780

**Comment by derekpock** [comment]
I will see if I can replicate the issue with #780 in place.

**Comment by derekpock** [comment]
I'm having trouble compiling it. I pulled the git repository and merged the 3 (really 2) files that #780 request committed, and I'm lost at how to compile the source. I think you use cmake, but I can't figure out what to do...

**Comment by eXpl0it3r** [comment]
Take a look at the [offical tutorial](http://www.sfml-dev.org/tutorials/2.2/compile-with-cmake.php).

**Comment by binary1248** [comment]
@derekpock: Any updates on this?

**Comment by derekpock** [comment]
As far as I can tell, I can't replicate the issue anymore. Either it was #780 that fixed it or the updated Elementary Freya software.
