### ISSUE TITLE
Add OpenGL 3 core context creation support

### ISSUE THREAD

**Issue by ecraven** [LaurentGomila/SFML#654]
Add support for creating an OpenGL core context. 

The default would still be a compatibility context, but there should be a way to create a core context, if explicitly wanted.
If you do this, you cannot use SFML Graphics (which still uses a compatibility context). It should be straightforward to add support for this (see for example http://en.sfml-dev.org/forums/index.php?topic=7903.msg53363#msg53363).

This gives users the option of using all the rest of SFML (save Graphics) and still get an OpenGL Core context.

**Comment by binary1248** [comment]
Will be added as part of #779.

**Comment by eXpl0it3r** [comment]
Hs been fixed through #779
