### ISSUE TITLE
ANDROID Application crash when switch to another application

### ISSUE THREAD

**Issue by JeromeOrtali** [LaurentGomila/SFML#755]
When you try to switch to another application without closing the SFML application , you cannot return inside, if you close the window when the event LostFocus appear and re-open the windows when the event GainnedFocus appear , the application crash too with this message inside logcat : 

<DequeueBuffer:606>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
<qeglDrvAPI_eglSwapBuffers:3688>: EGL_BAD_SURFACE

if you dont close the window , you have an : sfml-error failled to activate context inside logcat.

Minimal code here : http://pastebin.com/irUxWqyj

**Comment by fizixx** [comment]
On Android it is very important to handle the sf::Event::Closed event inside your main event loop.  If not, weird things happen or like in your case, it crashes when you switch applications.  See the example for details.

**Comment by JeromeOrtali** [comment]
The example crash too , with sf::Event::Closed too...

**Comment by MarioLiebisch** [comment]
Anything new on this issue? Closing this for now, as everything still points at some mistakes in user code (as pointed out above). Feel free to add more information in case you feel that the issue still exists (make sure to post a minimal example to reproduce the problem).

**Comment by naim42** [comment]
Seems like the issue still exists in 2.4.1 :/
I tried compiling and running the example inside the source directory, and I have the same problem: once I leave the activity, if I go back to it I see a black screen.
[This](http://pastebin.com/WTSRixtC) code doesn't work either.
Any information? I am compiling for android-23 on an armeabi-v7a architecture.

**Comment by DennisSc** [comment]
I can confirm that naim42's solution works like a charm - appending those four lines to my event loop fixed the crash on suspending/resuming:

```
if (event.type == sf::Event::LostFocus)
                    window.setActive(false);
                    
if (event.type == sf::Event::GainedFocus)
                    window.setActive(true);
```

thx
