### ISSUE TITLE
Ubuntu version is 1.6 while tutorial is 2.2

### ISSUE THREAD

**Issue by tfarina** [LaurentGomila/SFML#770]
How to install version 2.2 on Ubuntu?

**Comment by MarioLiebisch** [comment]
You should create a thread [on the official forums](http://en.sfml-dev.org/forums/). This bug tracker is for confirmed bugs in SFML. If a maintained package is outdated, contact the maintainer.

However, I just tried to install SFML using `apt-get` on Ubuntu 14.10 and I got the offer to install the SFML 2 packages (so everything seems to be fine).

If you can't (or don't want to) use the prebuilt binaries from the repository, clone this git repository and then build the libraries from scratch.

**Comment by tfarina** [comment]
Installed from source instead:

$ git clone https://github.com/LaurentGomila/SFML.git
$ cd SFML
$ mkdir build
$ cd build
$ cmake -GNinja -DSFML_BUILD_EXAMPLES=true ..
$ ninja
$ sudo ninja install
