### ISSUE TITLE
How to build for iOS.

### ISSUE THREAD

**Issue by xpol** [LaurentGomila/SFML#775]
I see there is [Tutorial: Building SFML for Android](https://github.com/LaurentGomila/SFML/wiki/Tutorial%3A-Building-SFML-for-Android)

But can find how to build for iOS.

**Comment by LaurentGomila** [comment]
Please use the forum, this tracker is for confirmed bugs and features, not for questions.

And search first, there is a post on the General > General Discussions forum that describes the steps required to compile the iOS port. There's no official or wiki tutorial for it yet.
