### ISSUE TITLE
SFML::saveToFile failed to save .jpg due to transparancy

### ISSUE THREAD

**Issue by gongenhao** [LaurentGomila/SFML#781]
sf::Image image_output;
image_output.create (width_render,height_render, imageData);
image_output.saveToFile(filename_output)

failed when the filename is specified as .jpg， works for .png
"JPEG parameter struct mismatch: library thinks size is 584, caller expects 568."

The imageData has 4 channels with transparency channel.
I understand .jpg does not support transparency but would you provide an auto work-around in the function since it is more stable and intuitive (just discard the 4th channel).
Thanks a lot.

**Comment by LaurentGomila** [comment]
This has nothing to do with the alpha channel or SFML at all. It's most likely a mismatch between your version of libjpeg, and the one SFML was compiled with.
