### ISSUE TITLE
Texture::loadFromImage() result is discarded in Font.cpp and Texture.cpp

### ISSUE THREAD

**Issue by varnie** [LaurentGomila/SFML#783]
Hi.
There're a few cases in Font.cpp and Texture.cpp where there's no checking whether or not the method
    
    Texture::loadFromImage
returns true, for example:

     //in Font.cpp
     texture.loadFromImage(image);
     page.texture.loadFromImage(newImage);

     //in Texture.cpp, copy-ctor
     if (copy.m_texture)
        loadFromImage(copy.copyToImage());

Was it intentional?

**Comment by LaurentGomila** [comment]
```Texture::loadFromImage``` can only fail if the size is either (0, 0) or greater than the maximum texture size supported by the GPU.

Now let's analyze the cases where it is not checked:

* Texture copy constructor: if the source texture is valid, then obviously creating a texture with the same size is valid too, therefore ```loadFromImage``` can't fail; another point is that we wouldn't have any way to signal a failure in a constructor without exceptions :)

* Font, texture.loadFromImage: the size is 2x2, which is not zero and way less than the maximum supported size -> cannot fail

* Font, page.texture.loadFromImage: the size is checked against the maximum supported size, so again, it cannot fail
