### ISSUE TITLE
Application with SFML 2.2 crashes on launch, 2.1 works fine on OSX 10.10.1

### ISSUE THREAD

**Issue by olbrew** [LaurentGomila/SFML#787]
Title basically says it all.
I'm  on OS X 10.10.1 Yosemite, all updates applied. Latest version of command line tools.
I installed SFML 2.2 and only use the frameworks.
I have a small graphical application that worked perfectly with SFML 2.1.
With 2.2 it shows an empty window and crashes after a second with a segmentation fault.

**Comment by MarioLiebisch** [comment]
Any hints or a minimal example? How about a stack trace? Launch the program compiled with debug symbols through **gdb** (`gdb yourexecutable`, then `run`), once it tells you about the segmentation fault (or any other problem), use the command `bt` and copy the output here.

**Comment by LaurentGomila** [comment]
Please use the forum for help requests. This tracker is for confirmed bugs and features.

**Comment by olbrew** [comment]
Sorry, didn't know that. @MarioLiebisch I made a mirror of this issue with the extra requested info on the SFML forums. You can find it [here](http://en.sfml-dev.org/forums/index.php?topic=17364.0).
Hope this helps.
