### ISSUE TITLE
Give the possibility to configure/compile specified modules with cmake

### ISSUE THREAD

**Issue by dwarfman78** [LaurentGomila/SFML#798]
given this topic http://en.sfml-dev.org/forums/index.php?topic=17492.0 and this one : http://en.sfml-dev.org/forums/index.php?topic=17489

I'm writing this request to allow the user the possibility to choose within cmake which modules to configure for compilation.

This feature is usefull if one is wanting to use a submodule on a targeted system that is not allowing another module to be compiled on/for.

In my case, i am using sfml-network (and its dependency sfml-system) only, indeed the target system is a openwrt router which cannot run any X11/opengl/whatever is needed by others sfml modules.

thanks for the feedback.

**Comment by MarioLiebisch** [comment]
Guess this sounds reasonable. As a temporary workaround, you could just run `make sfml-network`, but you'd have to install the files manually.

Only downside/quirk I could think right now, would be the fact that you'd still install the full headers, even those for the modules not being built.

**Comment by LaurentGomila** [comment]
> As a temporary workaround, you could just run make sfml-network, but you'd have to install the files manually.

Nop, the problem is at configure time. As you noticed, selective compilation already possible with targets. But right now you still have to *configure* all the modules (and therefore find all the dependant libraries) even if you're only going to build sfml-network.

**Comment by MarioLiebisch** [comment]
Ah, right. The external/system dependencies not being bundled... completely forgot about those. Think this is actually rather easy to add, going to try it a bit later today if I find the time to do it.

**Comment by MarioLiebisch** [comment]
Okay, so we've got a small hen and egg problem here:

Theoretically, a module like *sfml-window* has to ensure its dependencies (here: *sfml-system*) are considered for building. As such you'd define the projects from top to bottom. However, for CMake to find/link dependencies properly, they have to be defined from bottom to top.

Not sure how to solve this without redundant dependency definitions in two locations.

**Comment by mantognini** [comment]
Just a quick morning thought: For sfml-system, let's assume the user always wants it (wouldn't make much sense otherwise and it simplify things a bit), then on the user side we could have SFML_BUILD_WINDOW/GRAPHICS/AUDIO/NETWORK where SFML_BUILD_WINDOW would be automatically set to true if SFML_BUILD_GRAPHICS is true.

Then on the implementation side, do we need something special besides if statements?

**Comment by MarioLiebisch** [comment]
Well, yes, I could just introduce all variables in one locations and wouldn't matter whether there's system or not.

I would have preferred putting everything into the macro used to create the target son the fly, but guess that's not going to happen that easily.

**Comment by LaurentGomila** [comment]
You can't do this into the macros, when they are called it's already too late (all the dependencies search is done before). These variables must be defined in a top-level CMakelists.txt (such as src/SFML) and the whole module directory must be skipped if the corresponding option is unchecked.

**Comment by MarioLiebisch** [comment]
@LaurentGomila Exactly my hen and egg problem. :)

But yeah, going with the top level approach.

**Comment by MarioLiebisch** [comment]
There you go. give it a try please. :)

**Comment by mantognini** [comment]
Superseded by #800
