### ISSUE TITLE
[Win] Generate "FocusLost" events when window is grabbed and moved?

### ISSUE THREAD

**Issue by TheWehe** [LaurentGomila/SFML#801]
AfaIk there's no way to handle this problem (at least on Windows) at the moment. It would be really useful.
The only workaround I know is the way Rickety Raquet (http://www.ricketyracquet.de/) does it:
Prevent the user from using the mouse completely, so he's not able to move the window until he opens up the menu.
Is there a more simple solution? And if not, is it worth to become a feature?

**Comment by MarioLiebisch** [comment]
Could you clarify this a bit? What's the actual issue? Do you get `FocusLost` in case you move the window around? Or do you want to get the event if you try to move it?

Can you provide a minimal source code example to demonstrate the issue? Closing this till then. You should discuss issues on the [official forum](http://en.sfml-dev.org/forums/) and open a bug once you've confirmed it's indeed a problem.

**Comment by TheWehe** [comment]
Ok, I'll move this to the forum.

**Comment by MarioLiebisch** [comment]
Ok, feel free to post here again once there's been some consensus, so we can reopen/update this.
