### ISSUE TITLE
Bug on Nvidia with shader and "uniform sampler2D texture;"

### ISSUE THREAD

**Issue by lamogui** [LaurentGomila/SFML#802]
On Nvidia (GeForce GT 620M) the default name of the texture passed as uniform variable "uniform sampler2D texture;" cause a conflict with the name of the fonction "texture". In fact the function GLSL texture2D, texture1D or texture3D are deprecated. So impossible to use them:  

 > 'texture2D' : function is deprecated and not available

And when I use the new texture() glsl function I have a beautiful

 >  error C1105: cannot call a non-function

The bug is present only on my Nvidia graphic card, not on intel integrated or on ATI they seems to accept texture as variable name and function name at the same time.

The bug is not-critical it can be fixed with a call to 

> Shader::setParameter(const std::string& name, CurrentTextureType)

and renaming the variable. But it could be interresting renaming the default name of the uniform sampler because somes examples will not run.

**Comment by MarioLiebisch** [comment]
Did you define any specific shader version in your shader source? Could you provide some minimum example?

**Comment by binary1248** [comment]
You haven't said on what operating system (and what version of SFML) this occurs.

The example fragment shaders omit any `#version` directive which means that they must be parsed as version 1.10 according to the specification. In 1.10, `texture` was not yet a built-in function and could be used as a name.

[GLSL 1.30 specification with changes highlighted](https://www.opengl.org/registry/doc/GLSLangSpec.Full.1.30.08.withchanges.pdf).

The examples don't request a 3.0+ context, so in that case 1.30 cannot be forced anyway. This must be one of those many annoying Nvidia GLSL bugs.

I guess renaming the variable from `texture` to `the_texture` or something should fix the problem.

**Comment by lamogui** [comment]
yep the bug appear both on

> #version 330

and 

> #version 140

I didn't try other version
The code is the pixelate.frag example from the sfml (just replaced the "texture2D" by "texture"). 

```
uniform sampler2D texture;
uniform float pixel_threshold;

void main()
{
    float factor = 1.0 / (pixel_threshold + 0.001);
	vec2 pos = floor(gl_TexCoord[0].xy * factor + 0.5) / factor;
	gl_FragColor = texture(texture, pos) * gl_Color;	
}
```

Texture2D is deprecated since version GLSL 1.3 (130)

**Comment by lamogui** [comment]
Operating system Windows 7.

**Comment by binary1248** [comment]
Just to clarify, in case you didn't manage to read my previous comment before posting yours: _This is an Nvidia bug, not an SFML bug_. They don't follow the specification which requires the shader to be parsed as 1.10. We know that it won't work with versions 1.30+, but we aren't asking for it either.

**Comment by binary1248** [comment]
And before I forget: Did you modify the shader source and added a `#version` directive yourself or not?

If you did, then it isn't a bug at all. _The source won't work with `#version 130` or higher_. If you want to add the `#version` directive yourself, you will also have to make the required modifications to the shader source and example code as well.

**Comment by lamogui** [comment]
I added #version because Nvidia seems compile the shader with a higher version of GLSL (> 140) when no #version is specified.  Because I get errors: that some things are not available (ex: "global variable gl_Vertex is removed after version 140") when I didn't specify the #version.

And yes my drivers are up-to-date...

**Comment by binary1248** [comment]
So... there are other things (gl_Vertex) that wouldn't work as well if you don't specify a `#version`?

Can you paste the GLSL error log that is printed to the console when running the example _unmodified_ (nothing added or removed)?

**Comment by lamogui** [comment]
Ok, there is no error with fresh SFML compiled example without doing anything... I don't understand why... May be it's due to my configuration on my app with Nvidia Control Panel. 
However, the name texture remain an issue if you use more recent GLSL.

**Comment by binary1248** [comment]
> However, the name "texture" remain an issue if you use more recent GLSL.

__If__ we use more recent GLSL, which we don't.

We are aware that the examples (and even SFML shaders themselves) won't work with newer GLSL, which is why we don't request it in any of the examples. As an example, a lot of the API would have to be changed just to support user-defined vertex attributes.

We will approach this problem at a later time. For now, just remember that SFML's shaders aren't supposed to work with newer GLSL, and this is intentional.
