### ISSUE TITLE
Non-ASCII symbols in Sensor.hpp

### ISSUE THREAD

**Issue by BlaXpirit** [LaurentGomila/SFML#806]
There is the symbol `²` [**here**](https://github.com/LaurentGomila/SFML/blob/45810a134505f9d21d58f35f30d05d44c4a3db59/include/SFML/Window/Sensor.hpp#L52), and because of it the file *Sensor.hpp* can't be encoded as ASCII.

The main problem is, this file is for some reason encoded as *latin-1*, which is just a legacy locale-specific encoding that is still used pretty much only on Windows. Even your browser most likely won't display it correctly (if you open the [raw file](https://raw.githubusercontent.com/LaurentGomila/SFML/45810a134505f9d21d58f35f30d05d44c4a3db59/include/SFML/Window/Sensor.hpp))

I noticed this when my code parser choked on CSFML's *Sensor.h*, saying it's not valid UTF-8 (this problem has just been copied to CSFML in [this commit](https://github.com/LaurentGomila/CSFML/commit/fb1824b3b08ff34ec7b863c5937608916dfe5ba4#diff-47220121eccf287e8d46279cefb31a1aR42)). 

This is also broken [in the documentation](http://www.sfml-dev.org/documentation/2.2/classsf_1_1Sensor.php#a687375af3ab77b818fca73735bcaea84), which is supposed to be UTF-8, but actually isn't valid UTF-8.

An obvious fix would be to just change the encoding of this file to *UTF-8*, and that would work better.

(Side note: both *latin-1* and *UTF-8* are supersets of *ASCII*, so one could say every header file right now is encoded as *latin-1*, and every header file except this one is encoded as *ASCII* or *UTF-8*)

But I suggest to just change this to `^2`, because this tiny quirk in just one place is not worth potentially breaking some things that expect ASCII-only.

**Comment by eXpl0it3r** [comment]
Every other file is already UTF-8 encoded, guess this one was overlooked.
Do you have anything in mind that can only deal with ASCII?

**Comment by BlaXpirit** [comment]
Nothing in particular, just saying it's not worth the risk, however small.

2015-02-27 0:02 GMT+02:00 Lukas Dürrenberger <notifications@github.com>:

**Comment by LaurentGomila** [comment]
Let's go for ```^2```.

**Comment by eXpl0it3r** [comment]
Superseded by #807
