### ISSUE TITLE
sf::Music doesn't stop for FLAC files

### ISSUE THREAD

**Issue by eXpl0it3r** [LaurentGomila/SFML#814]
I guess here's the first issue regarding the just merged libsndfile branch.

The following short example reproduces the issue where playing a FLAC file with `sf::Music` never changes the playing status even after it finished playing.

```c++
#include <SFML/Audio.hpp>
#include <SFML/System.hpp>
#include <iostream>

int main()
{
	sf::Time duration;

	sf::Music music;
	music.openFromFile("sound.flac");
	music.play();

	while(music.getStatus() == sf::Music::Playing)
	{
		duration += sf::seconds(0.5f);
		sf::sleep(sf::seconds(0.5f));

		if(duration > music.getDuration())
			std::cout << "Oops" << std::endl;
	}

	// Never reached
}
```

**Comment by eXpl0it3r** [comment]
There seem to be further issues with FLAC and `sf::Music`. For example [this FLAC file](http://my-gate.net/pub/ding.flac) doesn't play at all with `sf::Music` but has no issue with `sf::Sound` and as "usual" it fails to change the playing status.

**Comment by mantognini** [comment]
I only tested [canary.flac](http://1drv.ms/1F6ajaU), which I've built from canary.wav using `flac` utility program. Does it work on your system?

If the current impl is too instable, we still can revert it and reopen the PR.

**Comment by eXpl0it3r** [comment]
That seems to work as well and the previous `song.flac` worked too. The current FLAC file is with ~2s rather short, not sure if that has any influence.

With your `canary.flac` it still doesn't change the playing status.

The master isn't supposed to be the most stable thing ever (anymore). The goal of the PR was to change the implementation to not use libsndfile anymore and that it was successful at. Bugs originating from that implementation can now be further found and corrected.
If a random PR breaks something we also don't revert and restore the PR just to fix the new issue. :wink:

**Comment by LaurentGomila** [comment]
The difference between sf::SoundBuffer and sf::Music, and that may explain the bug, is the following:
- sf::SoundBuffer gets the total number of samples declared by the sound file and reads exactly this amount of samples, in one shot
- sf::Music never requests the total number of samples, it stops when the read() function returns less than what it wanted

**Comment by mantognini** [comment]
> The master isn't supposed to be the most stable thing ever (anymore).

I agree with that, however were this issue block the next release, it would be easier to revert it now than later due to potential conflict with other PRs. But let's see if we can fix it within a few days. :-)

**Comment by binary1248** [comment]
> I agree with that, however were this issue block the next release, it would be easier to revert it now than later due to potential conflict with other PRs.

What issue? This has already been fixed in #817. :grin:

**Comment by mantognini** [comment]
You're too fast, man! :D

I'll check it out in a bit.

**Comment by eXpl0it3r** [comment]
Superseded by #817
