### ISSUE TITLE
Cannot build from source on Windows due to inability to find FREETYPE_INCLUDE_DIRS

### ISSUE THREAD

**Issue by MorleyDev** [LaurentGomila/SFML#816]
Can recreate with simple series of batch script commands:

git clone https://github.com/LaurentGomila/SFML
cmake SFML -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
cmake --build .

Error occurs for both MinGW and Visual Studio 12 2013 generators

Results in:
cmake SFML -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: C:/tools/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/tools/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/tools/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/tools/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenGL: opengl32
-- Found GLEW: C:/Users/%USER%/tmpo/SFML/extlibs/libs-mingw/x64/libglew32.a
-- Found JPEG: C:/Users/%USER%/tmpo/SFML/extlibs/libs-mingw/x64/libjpeg.a
CMake Error at C:/ProgramData/chocolatey/lib/cmake.3.0.2/content/cmake-3.0.2-win32-x86/share/cmake-3.0/Modules/FindPackageHandleS
tandardArgs.cmake:136 (message):
  Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/ProgramData/chocolatey/lib/cmake.3.0.2/content/cmake-3.0.2-win32-x86/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.c
make:343 (_FPHSA_FAILURE_MESSAGE)
  C:/ProgramData/chocolatey/lib/cmake.3.0.2/content/cmake-3.0.2-win32-x86/share/cmake-3.0/Modules/FindFreetype.cmake:138 (FIND_PACKAGE_HANDLE_STANDARD_ARGS) src/SFML/Graphics/CMakeLists.txt:124 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/%USER%/tmpo/CMakeFiles/CMakeOutput.log".

**Comment by eXpl0it3r** [comment]
Happens to the best of us. :wink:

I moved the update line to the top and made it stand out more, so it's immediately clear what happened to the issue.
