### ISSUE TITLE
Symlinks broken in FLAC.Framework for osx

### ISSUE THREAD

**Issue by nbollom** [LaurentGomila/SFML#818]
The symlinks for the Resources and Current are broken in the FLAC framework.

This causes a linking fail when building an application using SFML with the error:
>ld: framework not found FLAC

extlibs/libs-osx/Frameworks/FLAC.Framework/Versions/Current
should link to:
extlibs/libs-osx/Frameworks/FLAC.Framework/Versions/A/

extlibs/libs-osx/Frameworks/FLAC.Framework/Resources
should link to:
extlibs/libs-osx/Frameworks/FLAC.Framework/Versions/Current/Resources

**Comment by mantognini** [comment]
I guess something went wrong during a rebase operation... working on it.

**Comment by mantognini** [comment]
Superseded by #821.
