### ISSUE TITLE
Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by fizixx** [LaurentGomila/SFML#819]
I get this error when configuring CMake from the latest master checkout.

src/SFML/Graphics/CMakeLists.txt seem to refer to these:

    set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "${PROJECT_SOURCE_DIR}/extlibs/headers/libfreetype/windows")
    set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "${PROJECT_SOURCE_DIR}/extlibs/headers/libfreetype/windows/freetype")

But they don't exist.  I can't find a FindFreetype2.cmake file either.

**Comment by eXpl0it3r** [comment]
Make sure to empty your old build directory.

**Comment by eXpl0it3r** [comment]
Looks like I forgot to update these path. Strangely enough it worked fine for me.

**Comment by MorleyDev** [comment]
This is the same issue I had. I fixed by updating to the latest version of CMake, so it seems to be an incompatability with the previous versions of FindFreetype.cmake.

**Comment by eXpl0it3r** [comment]
Superseded by #820
