### ISSUE TITLE
KeyPressed event not fired with Shift + Tab

### ISSUE THREAD

**Issue by Breush** [LaurentGomila/SFML#826]
On Linux, there is no KeyPressed event fired for 'Tab' when doing LShift (holding it), then Tab.
Instead, it fires an 'Unknown' value.

This might be due to the fact that the corresponding keysym is an XK_ISO_Left_Tab,
which is not yet handled by SFML.
See http://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h

Status for other key combinations and on other platforms untested.

**Comment by Breush** [comment]
Well, just noticed that it is already discussed in #7.

**Comment by binary1248** [comment]
So... do you think it's worth keeping this issue open? Like you said, it is a subset of what is already discussed in #7.
