### ISSUE TITLE
Any plans to make data types for mouse movement and sprite coordinates the same?

### ISSUE THREAD

**Issue by muhdmirzamz** [LaurentGomila/SFML#830]
Currently, mouse movement is in a struct with two integers but setting position of a sprite sets two floats. Any reason for the different data types?

**Comment by zsbzsb** [comment]
Mouse coordinates are always going to be in screen coordinates (pixels) and there is no half pixel mouse position. And in the future please use the forums for such requests since the tracker is for confirmed issues/features.

**Comment by eXpl0it3r** [comment]
As @zsbzsb hinted, mouse position are in the pixel/screen space, while sprites and a like a in the world space. If you zoom the view the world coordinates won't match the screen coordinates. That's why the two functions mapPixelToCoords and mapCoordsToPixel.
