### ISSUE TITLE
WAV files with 32 bits per file don't work with sf::Music when 16 bits per file WAV files do.

### ISSUE THREAD

**Issue by robertmassaioli** [LaurentGomila/SFML#834]
Here are two example files:

 * [32 bits per file example][1]
 * [16 bits per file example][2]

The easiest way to test these is by replacing the orchestral.ogg file with these and then run the sound example.

The two sample files were generated using libsndfile based on an original WAV file that I have. If you have any more questions then please let me know.

 [1]: https://s3.amazonaws.com/uploads.hipchat.com/10804/83693/0faMzNh4zU8d09A/out-1.wav
 [2]: https://s3.amazonaws.com/uploads.hipchat.com/10804/83693/LCNBWx7dNB7BreK/out-1.wav

**Comment by robertmassaioli** [comment]
This issue was discovered while looking into: https://github.com/LaurentGomila/SFML/issues/541

**Comment by LaurentGomila** [comment]
Thanks for the report, I'll have a look.

**Comment by robertmassaioli** [comment]
Thankyou for looking so quickly! I meant to say 32 bits per sample but obviously you worked out what I meant. 

SFML is awesome BTW. Nice work on this library. If you need testing help then just let me know.

**Comment by LaurentGomila** [comment]
The fix is in #835.

**Comment by robertmassaioli** [comment]
You rock @LaurentGomila.
