### ISSUE TITLE
Linux KeyPressed events broken

### ISSUE THREAD

**Issue by harikattar** [LaurentGomila/SFML#847]
Pressing 1 results in the Event::KeyPressed code=Keyboard::Num1 as expected.
However, pressing <shift>+1 returns Keyboard::LShift then Keyboard::Unknown events.

Patch pending.

**Comment by mantognini** [comment]
Looks like dup of #7 to me. Let me know if I'm wrong.

**Comment by harikattar** [comment]
No, it's not the same issue, although if someone eventually fixes #7 the complete rewrite of keyboard handling will probably fix this as well.  Until then, my patch allows keystrokes on a standard keyboard to register on X11.

**Comment by Bromeon** [comment]
By the way, it's usually enough if you create a pull request alone (without additional issue), as it already contains the description of the issue. Even better would be to check existing issues first and discuss the matter on the forum, as described in the [contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks! :)

**Comment by Bromeon** [comment]
By the way, it's usually enough if you create a pull request alone (without additional issue), as it already contains the description of the issue. Even better would be to check existing issues first and discuss the matter on the forum, as described in the [contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks! :)
