### ISSUE TITLE
sf::Mouse::getPosition(window) returns global/desktop position rather than relative to window in Linux

### ISSUE THREAD

**Issue by edburnett** [LaurentGomila/SFML#860]
Something seems to have recently broken the ability for sf::Mouse::getPosition() to return the position relative to the SFML window rather than the overall desktop coordinates. 

Passing in the current sf::RenderWindow object vs not passing it in now returns the same value.
```
position = sf::Mouse::getPosition(window);
```
I'm using the git master branch on Archlinux x86_64.

Building SFML from the 2.2 release tag restores the expected behaviour.

**Comment by binary1248** [comment]
Try [this](https://github.com/LaurentGomila/SFML/pull/861).

**Comment by edburnett** [comment]
Yes, that fix works for me.

Thanks!
