### ISSUE TITLE
use user default locale for error messages

### ISSUE THREAD

**Issue by Heather** [LaurentGomila/SFML#866]
Example of issue:

``` shell
Failed to open sound file "resources/canary.wav" (System error : ╤шёЄхьх эх єфрхЄё  эрщЄш єърчрээ√щ яєЄ№.
)
Failed to open sound file "resources/orchestral.ogg" (System error : ╤шёЄхьх эх єфрхЄё  эрщЄш єърчрээ√щ яєЄ№.
)
```

**Comment by eXpl0it3r** [comment]
I don't quite follow? Do you want the error messages to be in your language?

**Comment by Heather** [comment]
@eXpl0it3r in my locale

**Comment by eXpl0it3r** [comment]
Can you describe things better? I still don't get it.

**Comment by Heather** [comment]
@eXpl0it3r `╤шёЄхьх эх єфрхЄё  эрщЄш єърчрээ√щ яєЄ№.` is Russian text but in my terminal it desplayd using wrong charset that's why I see what I see (random characters). I want to see it in readable charset, as Russian text.

**Comment by zsbzsb** [comment]
So are you suggesting that SFML should contain translations of error messages and then print the messages in the current user's language?

**Comment by Bromeon** [comment]
He's talking about the charset, not the language.

Isn't this a console rather than a locale problem? Is your terminal able to display non-ASCII characters?

**Comment by binary1248** [comment]
This is probably the result of libsndfile returning the localized Windows error string in UTF-16 and us dumping it to `std::cout` instead of `std::wcout`. Since we no longer use libsndfile, I don't know if we should even consider this a problem any more.

**Comment by Heather** [comment]
@Bromeon it's windows console, it can't print Russian characters if it will be printed in correct locale
@binary1248 it could be utf-8 , no need for utf-16 , just should use correct locale / charset

**Comment by Heather** [comment]
``` cpp
#include <iostream>

int main() {
  std::cout << "Тест" << std::endl;
  setlocale(LC_ALL, "");
  std::cout << "Тест" << std::endl;
```

``` shell
╥хёЄ
Тест
```

**Comment by binary1248** [comment]
Windows doesn't support UTF-8, that's why I said UTF-16.

**Comment by Heather** [comment]
@eXpl0it3r yes, at least default terminal but it's possible just to use correct locale as in example to display characters in correct way and don't mess code with wchars / tchars

**Comment by binary1248** [comment]
[Documentation for `setlocale`](https://msdn.microsoft.com/en-us/library/x99tb11d.aspx).

> The locale argument can take a locale name, a language string, a language string and country/region code, a code page, or a language string, country/region code, and code page. The set of available locale names, languages, country/region codes, and code pages includes all those supported by the Windows NLS API except code pages that require more than two bytes per character, such as UTF-7 and UTF-8. If you provide a code page value of UTF-7 or UTF-8, setlocale will fail, returning NULL.

> setlocale( LC_ALL, "" );
>     Sets the locale to the default, which is the user-default ANSI code page obtained from the operating system.

You are setting your locale to whatever is the default for your system, which makes the console take surrogate pairs (UTF-16) as input and is why your code works. If you try to pass it "real" UTF-8 data, you will find out that it still doesn't print it properly.

**Comment by Heather** [comment]
@binary1248 it's not `UTF-16` nor multibyte, `"this"` is basically `char*` but charset is `Russian_Russia.1251` in my case...

**Comment by TankOs** [comment]
@Heather It doesn't only depend on the set locale, but also on the encoded data you are going to output (this has been said already, I'm just trying to rephrase ;)). In case of sndfile's errors, it might be using your system's locale for encoding its error messages, but other endpoints might use UTF-8 or something else for encoding, which will mess up the output again.

There's no general solution to this. My best bet is setting the locale to UTF-8 -- at least SFML's internal error messages are encoded that way (source files are UTF-8). But if you are fine setting it like you did, then just do it. I don't think it should be part of SFML, though.

**Comment by Heather** [comment]
@TankOs I don't clearly understand, may you point the source where this error comes from?

**Comment by binary1248** [comment]
Like I already said in my first comment... libsndfile uses `FormatMessage` to get the error message string [here](https://github.com/erikd/libsndfile/blob/1710d1a82d3cfdc3a69fd6b224b4ed7c47d556b8/src/file_io.c#L825) with a language identifier of `MAKELANGID (LANG_NEUTRAL, SUBLANG_DEFAULT)` which for you is your system language.

__Important: We no longer use libsndfile in the latest SFML revision, so your problem no longer exists in master. If you try out the master branch you will not have this problem.__

**Comment by Heather** [comment]
@binary1248 oh... great. I will try `master` and reopen if there will be same behaviour
